import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {webcrypto as crypto} from 'node:crypto';
const require=createRequire(import.meta.url);
const {build}=createRequire(require.resolve('wrangler/package.json'))('esbuild');
const scratch=new URL('../.test-output/',import.meta.url);mkdirSync(scratch,{recursive:true});
const sqlite=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())sqlite.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8').replaceAll('--> statement-breakpoint',''));
const d1={prepare(sql){const stmt=sqlite.prepare(sql);let params=[];const api={bind(...p){params=p;return api;},async first(){return stmt.get(...params)||null;},async all(){return {results:stmt.all(...params)};},async run(){const r=stmt.run(...params);return {meta:{changes:Number(r.changes)}};}};return api;},async batch(queries){sqlite.exec('BEGIN');try{const out=[];for(const q of queries)out.push(await q.run());sqlite.exec('COMMIT');return out;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
globalThis.__TEST_ENV__={DB:d1,CRON_SECRET:'test-only-scheduler-secret',SITE_ORIGIN:'https://test.invalid'};
await build({entryPoints:['app/api/[...path]/route.ts','lib/model.ts','server/push.ts','server/prayers.ts','lib/location.ts'],outdir:scratch.pathname,bundle:true,platform:'node',format:'esm',entryNames:'[name]',plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test-env'}));b.onLoad({filter:/.*/,namespace:'test-env'},()=>({contents:'export const env=globalThis.__TEST_ENV__',loader:'js'}));}}]});
const {GET,POST}=await import(pathToFileURL(scratch.pathname+'route.js'));
const m=await import(pathToFileURL(scratch.pathname+'model.js'));
const push=await import(pathToFileURL(scratch.pathname+'push.js'));
const prayers=await import(pathToFileURL(scratch.pathname+'prayers.js'));
const locations=await import(pathToFileURL(scratch.pathname+'location.js'));
let now=Date.parse('2026-09-10T11:00:00+03:00');const realNow=Date.now;Date.now=()=>now;
const p={date:'2026-09-10',imsak:'05:00',sunrise:'06:20',noon:'12:50',afternoon:'16:20',sunset:'19:10',night:'20:30'};
const s={...m.defaults,districtId:'12345'};
const plan=m.buildPlan(p,s);
assert.equal(m.clock(plan.find(x=>x.key.endsWith(':wake')).at),'06:00');
assert.equal(m.clock(plan.find(x=>x.key.endsWith(':move')).at),'06:10');
assert.equal(m.clock(plan.find(x=>x.key.endsWith(':nap')).at),'13:10');
assert.equal(m.dateTR(plan.find(x=>x.key.endsWith(':work-end')).at),'2026-09-11');
const off=m.buildPlan(p,{...s,offDays:[p.date]});assert.equal(off.filter(x=>x.kind==='work').length,0);assert.equal(off.filter(x=>x.kind==='prayer').length,plan.filter(x=>x.kind==='prayer').length);
const skip=m.buildPlan(p,{...s,skippedNaps:[p.date]});assert(!skip.some(x=>x.kind==='nap'));assert(skip.some(x=>x.key.endsWith(':nap-skipped')));
assert(m.sleepInfo(p,s).recovery>=180);assert.throws(()=>m.validateSettings({sleepTarget:4},s));assert.throws(()=>m.validateSettings({bedtime:'25:10'},s));
console.log('PASS: daily offsets, midnight shift, days off, missed nap and sleep guardrails');
const originalFetch=globalThis.fetch;
const accepted=[];let prayerRequests=0;let prayerOutage=false;
globalThis.fetch=async(input,init)=>{
 const url=String(input);
 if(url.includes('/ilceler/'))return Response.json([{IlceID:9206,IlceAdi:'ANKARA'},{IlceID:'9207',IlceAdi:'AYAŞ'}]);
 if(url.includes('/sehirler/'))return Response.json([{SehirID:506,SehirAdi:'ANKARA'}]);
 if(url.includes('/vakitler/')){prayerRequests++;if(prayerOutage)throw Error('network offline');return Response.json(Array.from({length:3},(_,i)=>({MiladiTarihKisa:`${10+i}.09.2026`,Imsak:'05:00',Gunes:url.endsWith('9207')?'06:22':'06:20',Ogle:'12:50',Ikindi:'16:20',Aksam:'19:10',Yatsi:'20:30'})));}
 if(url.startsWith('https://web.push.apple.com/')){assert.equal(init.redirect,'manual','Workers push must not use unsupported error mode or follow redirects');accepted.push({url,init});return new Response('',{status:201});}
 throw Error('Unexpected external request '+url);
};
async function request(path,body,cookie='',auth=''){return (body===undefined?GET:POST)(new Request('https://test.invalid/api/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Gun-Akisi':'1',cookie,...(auth?{Authorization:auth,'X-Gun-Akisi-Trigger':'cron'}:{})},body:body===undefined?undefined:JSON.stringify(body)}));}
const first=await request('bootstrap',{});assert.equal(first.status,200);const cookie=first.headers.get('set-cookie').split(';')[0];const firstState=await first.json();assert.equal(firstState.settings.districtId,'9206');assert.equal(firstState.settings.prayerAreaName,'ANKARA');assert.equal(firstState.settings.districtName,'Etimesgut');assert.equal(firstState.prayerError,'');
const second=await request('bootstrap',{});const other=second.headers.get('set-cookie').split(';')[0];assert.notEqual(other,cookie);assert.equal((await request('state',undefined)).status,401);assert.equal((await request('tick',{},cookie)).status,401);
// Reproduce the real provider shape: Etimesgut is absent; IDs may be numeric.
assert.equal(locations.locationKey('  ETIMESGUT  '),locations.locationKey('Etimesgut'));
assert.equal(locations.locationKey('ŞEREFLİKOÇHİSAR'),locations.locationKey('sereflikochisar'));
assert.equal((await prayers.defaultLocation()).districtId,'9206');
const districtList=await(await request('locations?city=506')).json();assert(districtList.find(x=>x.id==='9206').aliases.includes('Etimesgut'));
const malformed=[null,{SehirID:506,SehirAdi:' ANKARA '},{SehirID:'bad',SehirAdi:'Ignore'},{SehirID:506,SehirAdi:'ANKARA'}];
assert.deepEqual(prayers.parseLocations(malformed,'city'),[{id:'506',name:'ANKARA'}]);
const sample={MiladiTarihKisa:'10.9.2026',Imsak:' 05:00 ',Gunes:'06:20',Ogle:'12:50',Ikindi:'16:20',Aksam:'19:10',Yatsi:'20:30'};
assert.equal(prayers.parsePrayerDays([sample,sample]).length,1);
assert.throws(()=>prayers.parsePrayerDays([{...sample,MiladiTarihKisa:'31.02.2026'}]));
assert.throws(()=>prayers.parsePrayerDays([{...sample,MiladiTarihKisa:'09.09.2026'}]));
assert.throws(()=>prayers.parsePrayerDays([{...sample,Gunes:'04:00'}]));
const beforeRefresh=prayerRequests;assert.equal((await request('refresh-plan',{},cookie)).status,200);assert.equal(prayerRequests,beforeRefresh+1);
// A real retry can refresh the cache, while today's validated cache survives an outage.
prayerOutage=true;assert.equal((await prayers.prayerDays('9206',true))[0].date,'2026-09-10');prayerOutage=false;
// Existing installs stuck with an empty district heal without clearing their device cookie.
const oldDevice=sqlite.prepare('SELECT id,settings FROM devices ORDER BY rowid LIMIT 1').get();
sqlite.prepare('UPDATE devices SET settings=? WHERE id=?').run(JSON.stringify({...JSON.parse(oldDevice.settings),districtId:''}),oldDevice.id);
const healed=await(await request('state',undefined,cookie)).json();assert.equal(healed.settings.districtId,'9206');assert.equal(healed.prayerError,'');
console.log('PASS: actual missing-Etimesgut shape, numeric location IDs, existing-install recovery, forced refresh, current-day validation');
const ecdh=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);
const subscription={endpoint:'https://web.push.apple.com/TEST',keys:{p256dh:push.b64(new Uint8Array(await crypto.subtle.exportKey('raw',ecdh.publicKey))),auth:push.b64(crypto.getRandomValues(new Uint8Array(16)))}};
assert.throws(()=>push.validateSubscription({...subscription,endpoint:'https://127.0.0.1/private'}));
const subscribed=await request('subscribe',{subscription},cookie);assert.equal(subscribed.status,200);let state=await subscribed.json();assert(state.events.length>0);assert.equal(state.scheduler.active,false);
const testNotification=await request('test-push',{},cookie);assert.equal(testNotification.status,200);assert(accepted.length>0);
assert.equal((await request('test-push',{},cookie)).status,429);
const oldIds=state.events.filter(x=>x.status==='pending').map(x=>x.id);
const changed=await request('settings',{revision:state.revision,settings:{districtId:'9207',cityId:'506'}},cookie);assert.equal(changed.status,200);state=await changed.json();assert.equal(state.settings.districtName,'AYAŞ');assert(sqlite.prepare('SELECT COUNT(*) as c FROM events WHERE id IN ('+oldIds.map(()=>'?').join(',')+") AND status='cancelled'").get(...oldIds).c>0);
// Administrative districts are independent of the provider's merged calendar areas.
const catalogue=JSON.parse(readFileSync(new URL('../server/data/turkey-districts.json',import.meta.url),'utf8'));
assert.equal(catalogue.length,81);assert.equal(catalogue.flatMap(x=>x.districts).length,973);
assert.equal(new Set(catalogue.flatMap(x=>x.districts.map(d=>d.id))).size,973);
const choices=await(await request('locations?city=506&administrative=1')).json();
assert.equal(choices.districts.length,25);
assert.equal(choices.districts.find(x=>x.name==='Etimesgut').prayerId,'9206');
assert(choices.districts.find(x=>x.name==='Etimesgut').aliases.includes('Eryaman'));
assert.equal(choices.districts.find(x=>x.name==='Sincan').prayerId,undefined,'Unverified calendars must be chosen explicitly');
assert.equal(choices.districts.find(x=>x.name==='Ayaş').prayerId,'9207');
const invalid=await request('settings',{revision:state.revision,settings:{adminDistrictId:'1757',districtId:'9206'}},cookie);
assert.equal(invalid.status,400,'District from another province must not be accepted');
assert.equal((await request('settings',{revision:state.revision,settings:{adminDistrictId:'1922',districtId:'9207'}},cookie)).status,400,'An exact/default calendar cannot be silently overridden');
const toEryaman=await request('settings',{revision:state.revision,settings:{adminDistrictId:'1922',districtId:'9206',regionName:'  Eryaman  '}},cookie);
assert.equal(toEryaman.status,200);state=await toEryaman.json();assert.equal(state.settings.regionName,'Eryaman');assert.equal(state.settings.districtName,'Etimesgut');assert.equal(state.settings.prayerAreaName,'ANKARA');
const beforeLabel=prayerRequests;
const labelOnly=await request('settings',{revision:state.revision,settings:{regionName:'Eryaman  1. Etap',districtName:'Fake',cityName:'Fake'}},cookie);
assert.equal(labelOnly.status,200);state=await labelOnly.json();assert.equal(state.settings.regionName,'Eryaman 1. Etap');assert.equal(state.settings.districtName,'Etimesgut');assert.equal(prayerRequests,beforeLabel,'Labels do not add external prayer fetches');
assert.throws(()=>m.validateSettings({regionName:'x'.repeat(81)},state.settings));assert.throws(()=>m.validateSettings({regionName:'x\ny'},state.settings));
const pendingBefore=sqlite.prepare("SELECT id FROM events WHERE device=? AND group_id='plan' AND status='pending'").all(oldDevice.id).map(x=>x.id);
const explicitArea=await request('settings',{revision:state.revision,settings:{adminDistrictId:'1747',districtId:'9206'}},cookie);
assert.equal(explicitArea.status,200);state=await explicitArea.json();assert.equal(state.settings.districtName,'Sincan');assert.equal(state.settings.regionName,'');
assert(pendingBefore.every(id=>sqlite.prepare('SELECT status FROM events WHERE id=?').get(id).status==='cancelled'),'Same calendar, new administrative district still cancels prior reminders');
const legacyMove=await request('settings',{revision:state.revision,settings:{districtId:'9207'}},cookie);
assert.equal(legacyMove.status,200);state=await legacyMove.json();assert.equal(state.settings.adminDistrictId,'');assert.equal(state.settings.regionName,'');assert.equal(state.settings.districtName,'AYAŞ');
console.log('PASS: 81 provinces / 973 districts, Etimesgut + Eryaman, calendar validation, region normalization, legacy clients and reminder replacement');
const stale=await request('settings',{revision:0,settings:{workStart:'19:00'}},cookie);assert.equal(stale.status,409);
const id=crypto.randomUUID();assert.equal((await request('session/start',{id,kind:'focus'},cookie)).status,200);assert.equal((await request('session/start',{id,kind:'focus'},cookie)).status,200);assert.equal((await request('session/start',{id:crypto.randomUUID(),kind:'walk'},cookie)).status,400);
now+=7*60000;assert.equal((await request('session/action',{id,action:'pause'},cookie)).status,200);now+=11*60000;
const paused=await(await request('state',undefined,cookie)).json();assert.equal(paused.sessions[0].elapsed,7*60000);assert.equal((await(await request('state',undefined,other)).json()).sessions.length,0);
assert.equal((await request('session/action',{id,action:'resume'},cookie)).status,200);now+=18*60000;
const done=await(await request('state',undefined,cookie)).json();assert.equal(done.sessions[0].status,'completed');assert.equal(done.sessions[0].elapsed,25*60000);
assert.equal((await request('session/action',{id,action:'stop'},other)).status,400);
assert.equal((await request('session/start',{id:crypto.randomUUID(),kind:'nap'},cookie)).status,400);
console.log('PASS: independent device records, secure scheduler, invalid push endpoints, location cancellation, optimistic updates, pause/resume, completed timers');
const manual=await POST(new Request('https://test.invalid/api/tick',{method:'POST',headers:{Authorization:'Bearer test-only-scheduler-secret'}}));assert.equal(manual.status,200);assert.equal((await(await request('state',undefined,cookie)).json()).scheduler.active,false);
const tick=await request('tick',{},'', 'Bearer test-only-scheduler-secret');assert.equal(tick.status,200);const tickState=await(await request('state',undefined,cookie)).json();assert.equal(tickState.scheduler.active,true);const count=accepted.length;assert(count>0);await request('tick',{},'','Bearer test-only-scheduler-secret');assert.equal(accepted.length,count);
console.log('PASS: scheduler dispatch, heartbeat, no duplicate delivery on consecutive ticks');
// Decrypt a real generated Web Push record independently with HKDF.
const packet=new Uint8Array(accepted[0].init.body),salt=packet.slice(0,16),pub=packet.slice(21,86),cipher=packet.slice(86);
const serverKey=await crypto.subtle.importKey('raw',pub,{name:'ECDH',namedCurve:'P-256'},false,[]);
const shared=await crypto.subtle.deriveBits({name:'ECDH',public:serverKey},ecdh.privateKey,256);
const encoder=new TextEncoder();const clientPub=push.un64(subscription.keys.p256dh);
const context=new Uint8Array(14+65+65);context.set(encoder.encode('WebPush: info\0'));context.set(clientPub,14);context.set(pub,79);
// The literal has 14 bytes (including NUL).
const hk=await crypto.subtle.importKey('raw',shared,'HKDF',false,['deriveBits']);
const ikm=await crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt:push.un64(subscription.keys.auth),info:context},hk,256);
const k=await crypto.subtle.importKey('raw',ikm,'HKDF',false,['deriveBits']);
const cek=await crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt,info:encoder.encode('Content-Encoding: aes128gcm\0')},k,128);
const iv=await crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt,info:encoder.encode('Content-Encoding: nonce\0')},k,96);
const aes=await crypto.subtle.importKey('raw',cek,'AES-GCM',false,['decrypt']);
const plaintext=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv},aes,cipher));assert.equal(plaintext.at(-1),2);assert(JSON.parse(new TextDecoder().decode(plaintext.slice(0,-1))).title);
const auth=accepted[0].init.headers.Authorization;const jwt=auth.split('t=')[1].split(',')[0],jwtParts=jwt.split('.');const vapidKey=JSON.parse(sqlite.prepare("SELECT value FROM kv WHERE key='vapid'").get().value);
const verifyKey=await crypto.subtle.importKey('raw',push.un64(vapidKey.public),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);assert(await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},verifyKey,push.un64(jwtParts[2]),encoder.encode(jwtParts[0]+'.'+jwtParts[1])));
console.log('PASS: independent RFC 8291 payload decryption and VAPID signature verification');
// Custom reminders use the same closed-app dispatcher, independent of prayer/location revisions.
assert.equal(m.countdown((2*3600+26*60+9)*1000),'02 saat 26 dakika 09 saniye');
assert.equal(m.countdown(-1),'00 saat 00 dakika 00 saniye');
assert.equal(m.countdown(59999),'00 saat 01 dakika 00 saniye');
assert.equal(m.nextPrayer([p],m.at(p.date,'18:00')).name,'Akşam');
assert.equal(m.nextPrayer([p],m.at(p.date,'18:00')).at,m.at(p.date,p.sunset));
assert.equal(m.nextPrayer([p,{...p,date:'2026-09-11'}],m.at(p.date,'23:59')).name,'Sabah');
const customId=crypto.randomUUID(),customDue=now+60000;
const customInput={id:customId,title:'Ekmek al',description:'Tam buğday ekmeği ve domates.',due:customDue,mediaId:null};
const createdCustom=await request('reminders',customInput,cookie);assert.equal(createdCustom.status,200);
assert.equal((await request('reminders',customInput,cookie)).status,200,'Retry must not duplicate the reminder');
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM reminders WHERE id=?').get(customId).n,1);
assert.equal((await(await request('reminders',undefined,other)).json()).reminders.length,0,'Other devices cannot list reminders');
assert.equal((await request('reminders',{...customInput,revision:0},other)).status,400);
assert.equal((await request('reminders',{...customInput,id:crypto.randomUUID(),due:now-1},cookie)).status,400);
const customEvent='custom:'+customId+':0';
await request('tick',{},'','Bearer test-only-scheduler-secret');assert.equal(sqlite.prepare('SELECT status FROM events WHERE id=?').get(customEvent).status,'pending','Never send early');
now=customDue+1000;await request('tick',{},'','Bearer test-only-scheduler-secret');
assert.equal(sqlite.prepare('SELECT status FROM events WHERE id=?').get(customEvent).status,'sent');
const deliveredCount=accepted.length;await request('tick',{},'','Bearer test-only-scheduler-secret');assert.equal(accepted.length,deliveredCount,'No duplicate custom notification');
const customEventBody=JSON.parse(sqlite.prepare('SELECT payload FROM events WHERE id=?').get(customEvent).payload);assert.equal(customEventBody.body,customInput.description);assert.equal(customEventBody.url,'/?view=reminders&reminder='+customId);
const editId=crypto.randomUUID(),editInput={...customInput,id:editId,due:now+300000};
assert.equal((await request('reminders',editInput,cookie)).status,200);
assert.equal((await request('reminders',{...editInput,revision:0,title:'Yeni başlık',due:now+600000},cookie)).status,200);
assert.equal(sqlite.prepare('SELECT status FROM events WHERE id=?').get('custom:'+editId+':0').status,'cancelled');
assert.equal(sqlite.prepare('SELECT status FROM events WHERE id=?').get('custom:'+editId+':1').status,'pending');
assert.equal((await request('reminders',{...editInput,revision:0},cookie)).status,400,'Stale edits cannot replace a newer reminder');
let reminderState=await(await request('state',undefined,cookie)).json();
await request('settings',{revision:reminderState.revision,settings:{regionName:'Yeni bölge'}},cookie);
assert.equal(sqlite.prepare('SELECT status FROM events WHERE id=?').get('custom:'+editId+':1').status,'pending','Personal reminders survive location/settings changes');
reminderState=await(await request('state',undefined,cookie)).json();
await request('settings',{revision:reminderState.revision,settings:{reminders:false}},cookie);
assert.equal(sqlite.prepare('SELECT status FROM events WHERE id=?').get('custom:'+editId+':1').status,'cancelled');
reminderState=await(await request('state',undefined,cookie)).json();
await request('settings',{revision:reminderState.revision,settings:{reminders:true}},cookie);
assert.equal(sqlite.prepare('SELECT status FROM events WHERE id=?').get('custom:'+editId+':1').status,'pending','Unmuting restores custom reminders');
await request('reminders/delete',{id:editId},other);assert(sqlite.prepare('SELECT id FROM reminders WHERE id=?').get(editId));
await request('reminders/delete',{id:editId},cookie);assert.equal(sqlite.prepare('SELECT status FROM events WHERE id=?').get('custom:'+editId+':1').status,'cancelled');assert(!sqlite.prepare('SELECT id FROM reminders WHERE id=?').get(editId));
const waitingId=crypto.randomUUID();await request('reminders',{...customInput,id:waitingId,due:now+600000},other);
assert(!sqlite.prepare('SELECT id FROM events WHERE id=?').get('custom:'+waitingId+':0'));
await request('subscribe',{subscription},other);assert.equal(sqlite.prepare('SELECT status FROM events WHERE id=?').get('custom:'+waitingId+':0').status,'pending','Subscribing later restores saved reminders');
console.log('PASS: actual prayer countdown, custom create/edit/delete, ownership, due dispatch, retries, mute/unmute and subscription recovery');

const objects=new Map();globalThis.__TEST_ENV__.BUCKET={async put(id,bytes){objects.set(id,new Uint8Array(bytes));},async get(id,options){const value=objects.get(id);if(!value)return null;const r=options?.range;const out=r?value.slice(r.offset,r.offset+r.length):value;return {body:new Blob([out]).stream()};},async delete(id){objects.delete(id);}};
const png=Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jGqkAAAAASUVORK5CYII=','base64'));
async function upload(bytes,type='image/png',who=cookie){return POST(new Request('https://test.invalid/api/reminder-media',{method:'POST',headers:{cookie:who,'X-Gun-Akisi':'1','Content-Type':type,'X-File-Name':encodeURIComponent('Hatırlatma.png')},body:bytes}));}
assert.equal((await upload(png,'image/png','')).status,401);
assert.equal((await upload(new TextEncoder().encode('<script>alert(1)</script>'))).status,400,'Claimed PNG with HTML bytes is rejected');
assert.equal((await POST(new Request('https://test.invalid/api/reminder-media',{method:'POST',headers:{cookie,'X-Gun-Akisi':'1','Content-Length':String(11*1024*1024)},body:png}))).status,400);
const uploaded=await upload(png);assert.equal(uploaded.status,200);const media=await uploaded.json();assert.equal(media.type,'image/png');assert.equal(media.name,'Hatırlatma.png');assert(objects.has(media.id));
const fileUrl='https://test.invalid'+media.url;
const partial=await GET(new Request(fileUrl,{headers:{Range:'bytes=0-7'}}));assert.equal(partial.status,206);assert.equal(partial.headers.get('content-range'),`bytes 0-7/${png.length}`);assert.deepEqual(new Uint8Array(await partial.arrayBuffer()),png.slice(0,8));
assert.equal((await GET(new Request(fileUrl,{headers:{Range:'bytes=999999-'}}))).status,416);
const attachedId=crypto.randomUUID(),attachedInput={...customInput,id:attachedId,title:'ş'.repeat(80),description:'ş'.repeat(600),due:now+600000,mediaId:media.id};
assert.equal((await request('reminders',{...attachedInput,id:crypto.randomUUID()},other)).status,400,'Media ownership is enforced');
assert.equal((await request('reminders',attachedInput,cookie)).status,200);
await request('reminder-media/delete',{id:media.id},cookie);assert(objects.has(media.id),'Referenced files are retained');
const richPayload=JSON.parse(sqlite.prepare('SELECT payload FROM events WHERE id=?').get('custom:'+attachedId+':0').payload);assert.equal(richPayload.image,media.url);
await push.encryptPayload(subscription,JSON.stringify({...richPayload,id:'custom:'+attachedId+':0',receipt:'x'.repeat(32),expires:now+900000}));
const savedAttachment=(await(await request('reminders',undefined,cookie)).json()).reminders.find(r=>r.id===attachedId);assert.equal(savedAttachment.media.url,media.url);assert.equal(savedAttachment.description,attachedInput.description);
await request('reminders/delete',{id:attachedId},cookie);assert(!objects.has(media.id));assert.equal((await GET(new Request(fileUrl))).status,404);
const mp4=Uint8Array.from([0,0,0,24,...Buffer.from('ftypisom'),0,0,0,0,...Buffer.from('isommp42')]);const movieResponse=await upload(mp4,'video/mp4');assert.equal(movieResponse.status,200);assert.equal((await movieResponse.json()).type,'video/mp4');
console.log('PASS: bounded durable media, content sniffing, ownership, byte ranges, attachment cleanup and full UTF-8 push size');
Date.now=realNow;globalThis.fetch=originalFetch;sqlite.close();console.log('All critical checks passed. Fixture prayer data; real device delivery requires an iPhone.');
