'use client';
import {memo,useCallback,useEffect,useRef,useState} from 'react';
import {BellRing,Plus,CalendarDays,Clock3,ImagePlus,Film,Trash2,Pencil,LoaderCircle,X,ArrowUpRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {toast} from 'sonner';
import {dateTR,clock} from '@/lib/model';
import {MAX_MEDIA_BYTES,type Reminder,type ReminderMedia} from '@/lib/reminders';
const dateLabel=new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Istanbul',day:'numeric',month:'long',year:'numeric'});
function fields(due:number){const [date,time]=new Date(due+3*3600000).toISOString().slice(0,16).split('T');return {date,time};}
function emptyDraft(){return {id:crypto.randomUUID(),title:'',description:'',...fields(Math.ceil(Date.now()/60000)*60000+5*60000),revision:undefined as number|undefined,media:null as ReminderMedia|null};}
async function request(path:string,body?:unknown){const res=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-Gun-Akisi':'1'},body:body===undefined?undefined:JSON.stringify(body)});const result=await res.json() as any;if(!res.ok)throw Error(result.error||'İşlem tamamlanamadı.');return result;}
const statusLabels:Record<string,string>={pending:'Planlandı',sending:'Gönderiliyor',sent:'Gönderildi',failed:'Gönderilemedi',expired:'Süresi geçti',cancelled:'Gönderim kapalı',waiting:'Bekliyor'};
function Attachment({media}:{media:ReminderMedia}){return media.type.startsWith('video/')?<video className="reminder-attachment" src={media.url} controls playsInline preload="metadata"/>:<img className="reminder-attachment" src={media.url} alt={media.name} loading="lazy"/>;}

export default memo(function RemindersPanel({ready,subscribed,enabled,schedulerActive,onNavigate}:{ready:boolean;subscribed:boolean;enabled:boolean;schedulerActive:boolean;onNavigate:(view:string)=>void}){
 const [rows,setRows]=useState<Reminder[]>([]),[draft,setDraft]=useState(emptyDraft),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[loadError,setLoadError]=useState('');
 const [detail,setDetail]=useState<Reminder|null>(null),[deleting,setDeleting]=useState<Reminder|null>(null),[now,setNow]=useState(Date.now());
 const titleRef=useRef<HTMLInputElement>(null),fileRef=useRef<HTMLInputElement>(null),formRef=useRef<HTMLFormElement>(null),alive=useRef(true),opened=useRef(''),mutating=useRef(false);
 const load=useCallback(async()=>{try{const result=await request('reminders');if(!alive.current)return;setRows(result.reminders);setNow(result.now);setLoadError('');const id=new URLSearchParams(location.search).get('reminder');if(id&&opened.current!==id){opened.current=id;const item=result.reminders.find((r:Reminder)=>r.id===id);if(item)setDetail(item);}}catch(e){if(alive.current)setLoadError((e as Error).message);}finally{if(alive.current)setLoading(false);}},[]);
 useEffect(()=>{alive.current=true;if(ready)load();const sync=()=>{if(ready&&!mutating.current&&document.visibilityState==='visible')load();};const timer=setInterval(sync,30000);document.addEventListener('visibilitychange',sync);return()=>{alive.current=false;clearInterval(timer);document.removeEventListener('visibilitychange',sync);};},[ready,load]);
 const cleanMedia=(media:ReminderMedia|null)=>{if(media)request('reminder-media/delete',{id:media.id}).catch(()=>{});};
 const reset=()=>{cleanMedia(draft.media);setDraft(emptyDraft());setError('');};
 async function upload(file:File){
  if(mutating.current)return;if(file.size>MAX_MEDIA_BYTES){setError('Dosya en fazla 10 MB olabilir.');return;}
  mutating.current=true;setUploading(true);setError('');
  try{const res=await fetch('/api/reminder-media',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-Gun-Akisi':'1','X-File-Name':encodeURIComponent(file.name)},body:file});const result=await res.json() as ReminderMedia&{error?:string};if(!res.ok)throw Error(result.error||'Dosya yüklenemedi.');if(!alive.current){cleanMedia(result);return;}cleanMedia(draft.media);setDraft(x=>({...x,media:result}));}
  catch(e){if(alive.current)setError((e as Error).message);}finally{mutating.current=false;if(alive.current)setUploading(false);if(fileRef.current)fileRef.current.value='';}
 }
 async function save(event:React.FormEvent){
  event.preventDefault();if(mutating.current||!ready)return;setBusy(true);mutating.current=true;setError('');
  try{const due=Date.parse(`${draft.date}T${draft.time}:00+03:00`);const result=await request('reminders',{id:draft.id,title:draft.title,description:draft.description,due,mediaId:draft.media?.id||null,revision:draft.revision});setRows(result.reminders);setNow(result.now);setDraft(emptyDraft());toast.success('Hatırlatman kaydedildi.');}
  catch(e){setError((e as Error).message);}finally{mutating.current=false;setBusy(false);}
 }
 function edit(item:Reminder){if(mutating.current)return;cleanMedia(draft.media);setDraft({id:item.id,title:item.title,description:item.description,...fields(item.due),revision:item.revision,media:item.media});setError('');setDetail(null);requestAnimationFrame(()=>{formRef.current?.scrollIntoView({behavior:'smooth',block:'start'});titleRef.current?.focus({preventScroll:true});});}
 async function remove(){if(!deleting||mutating.current)return;mutating.current=true;setBusy(true);try{const result=await request('reminders/delete',{id:deleting.id});setRows(result.reminders);if(draft.id===deleting.id)reset();if(detail?.id===deleting.id)setDetail(null);setDeleting(null);toast.success('Hatırlatma silindi.');}catch(e){toast.error((e as Error).message);}finally{mutating.current=false;setBusy(false);}}
 const future=rows.filter(r=>r.due>=now),past=rows.filter(r=>r.due<now).sort((a,b)=>b.due-a.due);
 const cards=(items:Reminder[])=>items.map(item=><article className="reminder-card" key={item.id}>
  <button className="reminder-open" onClick={()=>setDetail(item)}><span className="reminder-thumb">{item.media?(item.media.type.startsWith('video/')?<Film size={24}/>:<img src={item.media.url} alt="" loading="lazy"/>):<BellRing size={22}/>}</span><span className="reminder-copy"><strong>{item.title}</strong>{item.description&&<span className="reminder-excerpt">{item.description}</span>}<span className="reminder-meta"><CalendarDays size={14}/>{dateLabel.format(item.due)}<Clock3 size={14}/>{clock(item.due)}</span></span><ArrowUpRight size={17}/></button>
  <div className="reminder-card-foot"><span className={'reminder-status status-'+item.status}>{item.delivered?'Telefonda gösterildi':statusLabels[item.status]||'Bekliyor'}</span><div><button className="icon-button" aria-label={item.title+' düzenle'} disabled={busy||uploading} onClick={()=>edit(item)}><Pencil size={16}/></button><button className="icon-button" aria-label={item.title+' sil'} disabled={busy||uploading} onClick={()=>setDeleting(item)}><Trash2 size={16}/></button></div></div>
 </article>);
 return <><div className="page-heading"><div><h1>Hatırlatmalar</h1><p>Tarih, saat ve mesajın.</p></div><span className="round-badge"><BellRing/></span></div>
 {(!subscribed||!enabled||!schedulerActive)&&<div className="notice reminder-notice"><BellRing size={18}/><span>{!subscribed?'Bildirim almak için bu telefonu bağla.':!enabled?'Bildirimler kapalı. Hatırlatmalarını kaydedebilirsin.':'Otomatik gönderim bağlantısı bekleniyor.'}</span><button onClick={()=>onNavigate('settings')}>Bildirim ayarları</button></div>}
 <div className="reminders-grid"><section className="reminders-list"><div className="section-top"><h2>Sırada <span className="reminder-count">{future.length}</span></h2></div>{loadError&&<div className="notice error" role="alert"><span>{loadError}</span><button onClick={load}>Yenile</button></div>}{loading?<div className="reminder-empty"><LoaderCircle className="spin"/>Yükleniyor…</div>:future.length?cards(future):<div className="reminder-empty"><BellRing size={30}/><h3>Sıradaki hatırlatman burada.</h3><p>Mesajını ve zamanını seçerek ekle.</p></div>}{past.length>0&&<><h2 className="reminder-past-heading">Geçmiş</h2>{cards(past)}</>}</section>
 <form ref={formRef} className="card reminder-form" onSubmit={save}><div className="section-top"><h2>{draft.revision===undefined?'Yeni hatırlatma':'Hatırlatmayı düzenle'}</h2><Plus size={21}/></div>
 <label className="field">Başlık<input ref={titleRef} value={draft.title} maxLength={80} placeholder="Örn. Fırından ekmek al" required disabled={busy} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>
 <label className="field">Açıklama<textarea value={draft.description} maxLength={600} placeholder="Hatırlamak istediğin ayrıntılar…" rows={4} disabled={busy} onChange={e=>setDraft({...draft,description:e.target.value})}/><span className="field-counter">{draft.description.length} / 600</span></label>
 <div className="reminder-date-fields"><label className="field">Tarih<input type="date" required min={dateTR()} value={draft.date} disabled={busy} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label className="field">Saat<input type="time" required step={60} value={draft.time} disabled={busy} onChange={e=>setDraft({...draft,time:e.target.value})}/></label></div>
 <p className="reminder-timing-note">Türkiye saati. Gönderim dakikalık kontrol edilir; telefona ulaşması gecikebilir.</p>
 <input ref={fileRef} type="file" className="sr-only" aria-label="Görsel veya video ekle" accept=".png,.jpg,.jpeg,.gif,.webp,.mp4,.mov,.m4v,image/png,image/jpeg,image/gif,image/webp,video/mp4,video/quicktime" disabled={busy||uploading} onChange={e=>{const file=e.target.files?.[0];if(file)upload(file);}}/>
 {draft.media?<div className="reminder-file"><div><Attachment media={draft.media}/><span>{draft.media.name}</span></div><button type="button" className="icon-button" aria-label="Ek dosyayı kaldır" disabled={busy||uploading} onClick={()=>{cleanMedia(draft.media);setDraft({...draft,media:null});}}><X size={17}/></button></div>:<button type="button" className="reminder-upload" disabled={busy||uploading||!ready} onClick={()=>fileRef.current?.click()}>{uploading?<LoaderCircle className="spin"/>:<ImagePlus/>}<span><b>{uploading?'Dosya yükleniyor…':'Görsel veya video ekle'}</b><small>PNG, JPG, GIF, WebP, MP4, MOV · En fazla 10 MB</small></span></button>}
 <p className="reminder-media-note">iPhone’da görsel ve video, bildirime dokunduğunda uygulamada açılır.</p>
 {error&&<p role="alert" className="reminder-form-error">{error}</p>}
 <button className="primary full" type="submit" disabled={busy||uploading||!ready}>{busy?<LoaderCircle className="spin" size={18}/>:<BellRing size={18}/>}Hatırlatmayı kaydet</button>
 {(draft.revision!==undefined||draft.title||draft.media)&&<button type="button" className="text-button center" disabled={busy||uploading} onClick={reset}>Vazgeç, yeni hatırlatma</button>}
 </form></div>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v){setDetail(null);if(new URLSearchParams(location.search).has('reminder'))history.replaceState(null,'','/?view=reminders');}}}><DialogContent className="app-dialog reminder-detail"><DialogHeader><DialogTitle>{detail?.title}</DialogTitle><DialogDescription>{detail&&`${dateLabel.format(detail.due)} · ${clock(detail.due)} · Türkiye saati`}</DialogDescription></DialogHeader>{detail?.description&&<p className="reminder-description">{detail.description}</p>}{detail?.media&&<Attachment media={detail.media}/>}<button className="secondary" disabled={busy||uploading} onClick={()=>detail&&edit(detail)}><Pencil size={17}/>Düzenle</button></DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!busy)setDeleting(null);}}><AlertDialogContent className="app-dialog"><AlertDialogHeader><AlertDialogTitle>Hatırlatma silinsin mi?</AlertDialogTitle><AlertDialogDescription>“{deleting?.title}” silinecek ve bekleyen bildirimi iptal edilecek.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Vazgeç</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();remove();}}>Sil</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
});
